### Crear un cliente
POST http://localhost:8081/api/v1/clientes
Content-Type: application/json

{
  "nombre": "Juan Perez",
  "email": "juan@mail.com",
  "telefono": "123456789",
  "direccion": "Calle Falsa 123"
}

### Listar clientes
GET http://localhost:8081/clientes

### Obtener cliente por ID
GET http://localhost:8081/clientes/1



### Crear un cliente (a través del Gateway)
POST http://localhost:8080/clientes
Content-Type: application/json

{
  "nombre": "Juan Perezzzzz",
  "email": "juan@mail.com",
  "telefono": "123456789",
  "direccion": "Calle Falsa 123"
}

### Listar clientes (a través del Gateway)
GET http://localhost:8080/clientes

### Obtener cliente por ID (a través del Gateway)
GET http://localhost:8080/clientes/1